name: Generate GitHub Stats

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate stats card
        run: |
          curl -L -o stats.svg \
          "https://github-readme-stats-nnjvw75xo-kingdaniels-projects.vercel.app/api?username=DanielFerreiraReis&show_icons=true&theme=github_dark&include_all_commits=true&count_private=true"

      - name: Generate top languages card
        run: |
          curl -L -o top-langs.svg \
          "https://github-readme-stats-nnjvw75xo-kingdaniels-projects.vercel.app/api/top-langs/?username=DanielFerreiraReis&layout=compact&langs_count=8&theme=github_dark"

      - name: Commit files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add stats.svg top-langs.svg
          git commit -m "Update GitHub stats" || exit 0
          git push