name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *" # atualiza todo dia
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Stats
        uses: anuraghazra/github-readme-stats@master
        with:
          username: DanielFerreiraReis
          show_icons: true
          theme: github_dark
          include_all_commits: true
          count_private: true
          output: stats.svg

      - name: Generate Top Languages
        uses: anuraghazra/github-readme-stats@master
        with:
          username: DanielFerreiraReis
          layout: compact
          theme: github_dark
          output: top-langs.svg

      - name: Commit files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add *.svg
          git commit -m "update readme stats" || echo "no changes"
          git push